// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcgbrziqukcmmtlaeoex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZ2JyemlxdWtjbW10bGFlb2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzE2MzUsImV4cCI6MjA2NjcwNzYzNX0.Y2jBEQIuGa3FugFH8AE9Yd3V-92jEqG_wJfyy8gUfrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);